CREATE TABLE IF NOT EXISTS MOVIES (DIRECTED_BY VARCHAR(255), YEAR VARCHAR(255),MOVIE_NAME VARCHAR(255));
INSERT INTO MOVIES (DIRECTED_BY, YEAR,MOVIE_NAME) VALUES ('Steven Spielberg','1983','E.T.');
INSERT INTO MOVIES (DIRECTED_BY, YEAR,MOVIE_NAME) VALUES ('Ridley Scott','1978','Alien');
INSERT INTO MOVIES (DIRECTED_BY, YEAR,MOVIE_NAME) VALUES ('James Cameroon','2009','Avatar');